# Studying the behavior of deeper multilayer perceptron
Here more than 1 hidden layers were implemented in order to compare its behavior to a single layer MLP.

In [1]:
# changing cwd
%cd ..

c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias


## Load packages

In [2]:
from src.inductive_bias import IB
ib = IB() #instantiate inductive bias package

[ c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias\clf\SimulationData.pickle ] loaded
[ c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias\clf\PosteriorData.pickle ] loaded
[ c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias\clf\TrainedCLF.pickle ] loaded
[ c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias\clf\EstimatedData.pickle ] loaded
[ c:\Users\jongm\Desktop\temp_workspace\JOVO\inductive-bias\clf\HellingerData.pickle ] loaded
Size of the S-XOR: (6322,)                    
Size of the Spiral: (6276,)                    
Size of the whole dataset: (12598, 7)

Size of the S-XOR after adding hellinger: (6322, 8)            
Size of the Spiral after adding hellinger: (6276, 8)


## Time and Date of the experiment

In [3]:
print(ib.date)

2021-09-08 00:16:52.002326


## Load Dependencies

In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
# import pickle
from tqdm import tqdm

import matplotlib.pyplot as plt
from matplotlib.patches import Circle

from mpl_toolkits.axes_grid1 import AxesGrid

cmap = 'PRGn'

# for figure 3
import matplotlib as mpl
from matplotlib.lines import Line2D #only for the purpose of creating the legend

import warnings
warnings.filterwarnings('ignore')

## main exp

In [5]:
np.array(ib.truepst).shape

(2, 5, 3, 739600)

In [6]:
ib.truepst[0][0]

(array([-4.3 , -4.29, -4.28, ...,  4.27,  4.28,  4.29]),
 array([-4.3 , -4.3 , -4.3 , ...,  4.29,  4.29,  4.29]),
 array([0.50001397, 0.50001397, 0.50001397, ..., 0.50001397, 0.50001397,
        0.50001397]))

In [13]:
# ib.clf[0][0][1].get_params()['hidden_layer_sizes']
# np.array(ib.clf).shape
ib.clf[0][2]

[NuSVC(probability=True),
 MLPClassifier(alpha=0, learning_rate_init=0.0001, max_iter=10000,
               solver='lbfgs'),
 RandomForestClassifier(max_depth=10, n_estimators=128, n_jobs=-1),
 QuadraticDiscriminantAnalysis()]

In [8]:
ib.get_MLPs(param=ib.clf)

AttributeError: 'list' object has no attribute 'get_params'